# -*- coding: utf-8 -*-
"""FireGuardML_Train

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1168kZoJstazYulFmyLx-aQmy8QjIwb-J
"""

#!nvidia-smi

"""To enable this option, you must change **Go to Runtime -> Change runtime type , and select “GPU” as the Hardware Accelerator**

## Install dependecy and test it
"""

#!pip install ultralytics

#!yolo predict model=yolov8n.pt source='https://media.roboflow.com/notebooks/examples/dog.jpeg'

"""## Get datasets from your own Google drive"""

# You must download the dataset from release and import it
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/D-Fire-datasets/fire

#!ls

#!cat data.yaml

"""## Start training model with YoloV8 and index with data.yaml"""

#!yolo task=detect mode=train model=yolov8s.pt data=data.yaml epochs=25 imgsz=416 plots=True

#!ls ./runs/detect/train3

"""## Checking training results"""

from IPython.display import display, Image
Image(filename='./runs/detect/train3/confusion_matrix.png', width=600)

Image(filename='./runs/detect/train3/results.png', width=600)

Image(filename='./runs/detect/train3/val_batch0_labels.jpg', width=600)

Image(filename='./runs/detect/train3/val_batch1_labels.jpg', width=600)

"""## Test the model with YOLOv8"""

#!yolo task=detect mode=predict model="./runs/detect/train3/weights/best.pt" source="./runs/detect/train3/val_batch0_labels.jpg"